---
- name: "Prepare the complyctl environment on the Demo VM"
  hosts: demo_vm
  become: false
  vars:
    # Update according to where https://github.com/complytime/complyctl.git was cloned
    complyctl_repo_dest: "~/GIT/ProdSec/complyctl"
    complyctl_workspace: "~/.local/share/complytime"

  tasks:
    - name: "Ensure removal of packages from previous installation"
      ansible.builtin.dnf:
        name:
          - complyctl
          - complyctl-openscap-plugin
        state: absent
      become: true

    - name: "Build complyctl locally"
      ansible.builtin.command:
        cmd: "make build"
        chdir: "{{ complyctl_repo_dest }}"
      delegate_to: localhost

    - name: "Ensure bin directory in home directory to make it easier to call complyctl"
      ansible.builtin.file:
        path: "~/bin"
        state: directory
        mode: "0750"

    - name: "Copy complyctl binary to Demo VM"
      ansible.builtin.copy:
        src: "{{ complyctl_repo_dest }}/bin/complyctl"
        dest: "~/bin/complyctl"
        mode: "0750"

    - name: "Ensure COMPLYTIME_DEV_MODE=1 is set for the testing user"
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: 'export COMPLYTIME_DEV_MODE=1'
        insertafter: EOF
        state: present

    - name: "Check existing complyctl directories in case there is already a Workspace"
      ansible.builtin.stat:
        path: "{{ complyctl_workspace }}"
      register: result_complyctl_workspace

    - name: "Initialize complyctl to ensure the Workspace is created"
      ansible.builtin.command:
        cmd: "~/bin/complyctl list"
      environment:
        COMPLYTIME_DEV_MODE: "1"
      failed_when: false
      changed_when: not result_complyctl_workspace.stat.exists
      when: not result_complyctl_workspace.stat.exists

    - name: "Copy OpenSCAP plugin binary to Demo VM"
      ansible.builtin.copy:
        src: "{{ complyctl_repo_dest }}/bin/openscap-plugin"
        dest: "{{ complyctl_workspace }}/plugins"
        mode: "0750"

    - name: "Compute SHA256 checksum of the openscap-plugin binary"
      ansible.builtin.stat:
        path: "{{ complyctl_workspace }}/plugins/openscap-plugin"
        checksum_algorithm: sha256
      register: result_plugin_checksum

    - name: "Create or update the openscap-plugin manifest"
      ansible.builtin.template:
        src: c2p-openscap-manifest.json.j2
        dest: "{{ complyctl_workspace }}/plugins/c2p-openscap-manifest.json"
        mode: "0640"
...
